#!/bin/sh
# run most py files

echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/armbruster.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/armbruster.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog2.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog2.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog3.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog3.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog4.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog4.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog4a.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/intprog4a.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/katsura.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/katsura.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/preimage.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/preimage.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/quantumplane_syz.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/quantumplane_syz.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/rose.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/rose.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/solvablemodule.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/solvablemodule.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/solvmodright.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/solvmodright.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syz.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syz.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzsolv.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzsolv.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzy2.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzy2.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzy3.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/syzy3.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/trinks.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/trinks.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/mark.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/mark.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_2_wa_1.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_2_wa_1.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_e.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_e.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_f.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_f.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_wa_1.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_2_wa_1.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_3.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_3.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_3_prod.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_sl_3_prod.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_so_3.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/u_so_3.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_1.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_1.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_32.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_32.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_32_syz.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/wa_32_syz.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/chebyshev.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/chebyshev.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/legendre.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/legendre.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/arith.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/arith.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/powerseries.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/powerseries.py
echo jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/polynomial.py
time jython -J-cp ../lib/log4j.jar:../lib/junit.jar:. -J-verbose:gc examples/polynomial.py
