#!/bin/bash
# script to call meditor with the jas engine
#
# $Id$

LIBPATH=~/java/lib
MEDITORPATH=~/java/meditor3.0
JASPATH=.

UTILS=$LIBPATH/jython.jar:$LIBPATH/log4j.jar

JAS=$JASPATH/jas.jar:$JASPATH/jas-meditor.jar

if [[ ! -f "jas.py" ]]; then
   cp $JASPATH/examples/jas.py .
fi

MEDITOR=$MEDITORPATH/meditor.jar:$MEDITORPATH/lib/jscl.jar

CLASSPATH=$UTILS:$JAS:$MEDITOR:.

mkdir -p test
java -classpath $CLASSPATH -Duser.home=$JASPATH/examples jscl.editor.Editor
