#!/bin/bash
# script to call meditor with the jas engine
#
# $Id: $

LIBPATH=~/java/lib
MEDITORLIB=~/java/meditor3.0/lib

UTILS=$LIBPATH/jython.jar:$LIBPATH/log4j.jar

MEDITOR=$MEDITORLIB/bsh-2.0b4.jar:$MEDITORLIB/fop.jar:$MEDITORLIB/google-api-translate-java-0.4.jar:$MEDITORLIB/jeuclid-core-3.0.3-PATCHED.jar:$MEDITORLIB/jeuclid-fop-3.0.3.jar:$MEDITORLIB/jlfgr-1_0.jar:$MEDITORLIB/stylesheets.jar:$MEDITORLIB/swing-layout-1.0.3.jar:$MEDITORLIB/jscl.jar

JAS=$LIBPATH/jas.jar::$LIBPATH/jas-meditor.jar

CLASSPATH=$UTILS:$JAS:$MEDITOR:$LIBPATH/meditor.jar

mkdir -p test
java -classpath $CLASSPATH jscl.editor.Editor
